# taken from https://github.com/nix-community/go-nix/blob/main/.golangci.yml
linters:
    enable-all: true
    disable:
        - depguard
        - exhaustruct
        - funlen
        - tenv
        - godox
        - mnd
        - varnamelen
        - forbidigo
        - gocognit
        - gocyclo
        - cyclop
        - err113
        - maintidx
        # would be nice to have but too many tests depend on environment variables, which is not allowed for t.Parallel()
        - paralleltest
        # would be also nice to enable because I also found some cases confusing
        - nonamedreturns
